deploy:
  runs-on: ubuntu-latest
  needs: build
  environment:
    name: "Production"
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  permissions:
    id-token: write
    contents: read

  steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: node-app

    - name: Unzip artifact for deployment
      run: unzip release.zip

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Restart Azure App Service (to avoid file lock)
      run: az webapp restart --name duanrac-api-node --resource-group YOUR_RESOURCE_GROUP

    - name: "Deploy to Azure Web App"
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: "duanrac-api-node"
        package: .
